services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: ""  # No build step needed
    startCommand: "python backend/main.py"  # Start your WebSocket server
    envVars:
      - key: PORT
        value: 8080

  - type: static
    name: frontend
    staticPublishPath: frontend  # Adjust if your frontend files are in a different folder
