services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: ""  # No build step needed
    startCommand: "python backend/main.py"  # Starts your WebSocket server
    envVars:
      - key: PORT
        value: 8080

  - type: web
    name: frontend
    env: static
    plan: free
    buildCommand: ""  # No build step needed
    staticPublishPath: frontend  # Ensure this contains `index.html`, `script.js`
